---
- hosts: localhost
  tasks:
    - name: Create a test file
      file:
        path: /tmp/testfile.txt
        state: touch
        mode: '0644'
    - name: Add content to test file
      copy:[📦 com.jetbrains.GoLand tmp]$ ls

        content: "Hello from AnsibleGitOps...cycle 3"
        dest: /tmp/testfile.txt
