---
- hosts: webservers
  tasks:
    - name: Create a test file v1
      file:
        path: /tmp/testfile.txt
        state: touch
        mode: '0644'
    - name: Add content to test file
      copy:
        content: "Hello from AnsibleGitOps...cycle 3"
        dest: /tmp/testfile.txt
        
